# Generated by Django 6.0.6 on 2026-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="avatar",
            field=models.TextField(blank=True, default="avatar_1", null=True),
        ),
    ]
