# Generated by Django 6.0.6 on 2026-06-26 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(default="system", max_length=20)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "downloads_folder",
                    models.CharField(default="Downloads", max_length=255),
                ),
                ("auto_accept", models.BooleanField(default=False)),
                ("bandwidth_limit", models.IntegerField(blank=True, null=True)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("privacy_mode", models.CharField(default="public", max_length=20)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="devices.device",
                    ),
                ),
            ],
        ),
    ]
